version: '3.8'

services:
  web:
    build: .
    container_name: hr_rag_app
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped